### PR TITLE
Fix generation of unnecessary Ptyp_poly nodes

### LINKED ISSUE #161: "broken invariant in parsetree: Explicit universal type quantification cannot be empty" with OCaml 5.3
While compiling the following interface file with OCaml 5.3 and only ppx_deriving_yojson:

https://framagit.org/zoggy/ojs-base/-/blob/3067edd2bf7f67f52b09dfb5a7b8914ada8d28f2/lib/types.mli

the following error message appears:

```
$ (cd _build/default && /home/kit_ty_kate/.opam/5.3/bin/ocamlc.opt -g -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -bin-annot -w -6-7-9-10-27-32-33-34-35-36-39-50-52 -no-strict-sequence -g -bin-annot -bin-annot-occurrences -I lib/.ojs_base.objs/byte -I /home/kit_ty_kate/.opam/5.3/lib/lwt -I /home/kit_ty_kate/.opam/5.3/lib/ppx_deriving/runtime -I /home/kit_ty_kate/.opam/5.3/lib/ppx_deriving_yojson/runtime -I /home/kit_ty_kate/.opam/5.3/lib/seq -I /home/kit_ty_kate/.opam/5.3/lib/yojson -no-alias-deps -opaque -open Ojs_base -o lib/.ojs_base.objs/byte/ojs_base__Types.cmi -c -intf lib/types.pp.mli)
File "_none_", line 1:
Error: broken invariant in parsetree: Explicit universal type quantification cannot be empty.
```
This issue doesn't appear with OCaml 5.2

### PR DESCRIPTION
**Pull request by NathanReb**
Fixes #161 

The deriver would always generate `Ptyp_poly` nodes, regardless of whether the type had parameters or not. We used to get away with it but starting with OCaml 5.3, the compiler now enforce this AST invariant that we were breaking.

### CODE REVIEW

File: src/ppx_deriving_yojson.ml [hunk 1]
```diff
@@ -319,6 +319,10 @@ let ser_str_of_record ~quoter ~loc varname labels =
   in
   [%expr let fields = [] in [%e assoc]]
 
+let possibly_poly_typ poly_vars ~polymorphize typ =
+  match poly_vars with
+  | [] -> typ
+  | _ -> Typ.poly poly_vars (polymorphize typ)
```
Comment (kit-ty-kate) [inline src/ppx_deriving_yojson.ml:325]: could it be better to change ppxlib instead? Replacing the definition of `Typ.poly` by `match poly_vars with [] -> typ | ...` would make sense i think if it's not allowed by the compiler. It would avoid the issue in other ppxs as well

Comment (NathanReb) [reply src/ppx_deriving_yojson.ml:325]: Yes that's a good idea. I'll add something in `Ast_builder` though as we don't recommend using `Ast_helper_lite`.

Comment (NathanReb) [reply src/ppx_deriving_yojson.ml:325]: Well, turns out `Ast_builder.Default.ptyp_poly` already does that!
